V1.2.0 dev (#16)
* adding init 1.2.0 changes

* controller changes

* controller rewrite to support pod labels

* agent now supports podlables, configurable prometheus, plugin auto discover

* chart changes to support new features

* updating CONTRIBUTING doc with accurate info

* restapi changes - wip

* latest dev images in chart

* restapi changes

* restapi fix

* bug fix for controller; restapi fix; remove binary

* restapi chages for new ui; bug fixes; version in configs

* refactor Makefiles, move to alpine

* more dockerfile changes

* small redis refactor, restapi detect redis.nil er

* bug fixes and prep for ui, using protojson instead of json

* remove multi-platform build

* Fix SelectRandomAgent

* Remove all buildfiles before building docker-all

* fix bug with controller, export CRD status to redis

* plugin discovery chagnes

* fix controller not updating redis if there are errs

* label and ns matching for agents, beter prom labels, py test

* move to buf for proto generation, add plugin back to summary

* python text experiment

* working python test, bug fixes

* python module

* remove python cache

* adding pyproject.toml

* update pyproject

* more python development, bug fixes

* fix python wrapper

* fix python wrapper

* fully working python plugin - json-ping

* push.sh file

* Create README.md

* merge Dockerfiles, use build stages

* chore: create missing directories

* fix bug where agent wont purge deleted test correctly

* chart chages and local testing configs

* chart image fix

* more docs - deployment models, logo, local debugging

* Markdown linting

* mnore Markdown linting

* mnore Markdown linting

---------

Co-authored-by: bakshi41c <bakshi41c@gmail.com>
Co-authored-by: BlitzQuiche <kieran.shave@live.com>
Co-authored-by: Marwa Ouled El Hadj Ali <mouledel@cisco.com>

diff --git a/agent/Makefile b/agent/Makefile
--- a/agent/Makefile
+++ b/agent/Makefile
@@ -1,15 +1,52 @@
+GOFLAGS=-ldflags=-w -ldflags=-s
+SYNTEST_PLUGIN_SUBDIRS = $(notdir $(wildcard ./plugins/syntests/*))
+LOCAL_BUILD_PATH=./bin
+
+## Agent
+build-go-syntest-plugins:
+	@echo "Building Go syntest plugins"
+	for dir in $(SYNTEST_PLUGIN_SUBDIRS); do \
+			echo "Building plugin: $$dir" && \
+			CGO_ENABLED=0 go build $(GOFLAGS) -o $(LOCAL_BUILD_PATH)/plugins/test-$$dir ./plugins/syntests/$$dir/ && \
+			echo "$$dir compiled!" || { echo "$$dir failed!"; exit 1; }; \
+	done
+
+build-agent-only:
+	@echo "Building agent"
+	CGO_ENABLED=0 go build $(GOFLAGS) -ldflags="-X main.Version=$(SYNHEART_VERSION)" -o $(LOCAL_BUILD_PATH)/agent .
+
+.PHONY: build-agent
+build-agent: build-agent-only build-go-syntest-plugins
+
 ## SDK - Creating new syntest plugin
 .PHONY : new-go-syntest
 new-go-syntest:
 	@echo Creating Directory plugins/syntests/$(name)
-	mkdir agent/plugins/syntests/$(name)
+	mkdir plugins/syntests/$(name)
 
 	@echo Creating file plugins/syntests/$(name)/$(name).go
-	cp agent/plugins/templates/go/test.tpl.go plugins/syntests/$(name)/$(name).go
+	cp plugins/templates/go/test.tpl.go plugins/syntests/$(name)/$(name).go
 
-	sed -i .backup s/{{TestName}}/$(call capitalize,$(name))/g  plugins/syntests/$(name)/$(name).go
-	rm agent/plugins/syntests/$(name)/$(name).go.backup
+	sed -i s/{{TestNameRaw}}/$(name)/g  plugins/syntests/$(name)/$(name).go
+	sed -i s/{{TestName}}/$(call capitalize,$(name))/g  plugins/syntests/$(name)/$(name).go
+
+.PHONY : new-python-syntest
+new-python-syntest:
+	@echo Creating Directory plugins/syntests-python/$(name)
+	mkdir -p plugins/syntests-python/$(name)
+
+	@echo Creating file plugins/syntests/$(name)/$(name).py
+	cp plugins/templates/python/test.tpl.py plugins/syntests-python/$(name)/test-$(name).py
+	cp plugins/templates/python/requirements.txt plugins/syntests-python/$(name)/requirements.txt
+
+	echo $(call camelcase,$(name))
+
+	sed -i s/{{TestName}}/$(call camelcase,$(name))/g  plugins/syntests-python/$(name)/test-$(name).py
 
 define capitalize
 $(shell echo $(1) | awk '{$$1=toupper(substr($$1,0,1))substr($$1,2); print $$0}')
+endef
+
+define camelcase
+$(shell echo $(1) | awk 'BEGIN{FS="";RS="-";ORS=""} {$$0=toupper(substr($$0,1,1)) substr($$0,2)} 1')
 endef
